# Generated by Django 4.2 on 2024-01-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_login_remove_customer_email_customer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password1',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
